[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    'solady/=lib/solady/src',
    'optimism/=lib/optimism/packages/contracts-bedrock/src',
    'transience/=lib/transience/src',
]
